name: 'Dispatch: Deploy Javadoc'

on:
  workflow_dispatch:
    inputs:
      target_tag:
        description: 'Version to generate javadoc'
        required: true

jobs:
  javadocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.target_tag }}

      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 11
          target-folder: javadoc
          project: gradle
